# Generated by Django 5.2.16 on 2026-07-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='medicines.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pharmacies.pharmacy')),
            ],
            options={
                'indexes': [models.Index(fields=['pharmacy', 'medicine'], name='inventory_i_pharmac_6ad3e8_idx'), models.Index(fields=['quantity'], name='inventory_i_quantit_ef61d1_idx'), models.Index(fields=['expiry_date'], name='inventory_i_expiry__faeaca_idx')],
                'unique_together': {('pharmacy', 'medicine')},
            },
        ),
    ]
