from django.conf import settings
from django.db import models
from django.core.exceptions import ValidationError
from pharmacies.models import Pharmacy
from inventory.models import Inventory


class Invoice(models.Model):
    """
    One bill generated by a pharmacy at the point of sale.

    WHY separate Invoice + InvoiceItem instead of one flat table?
    A single invoice can contain MULTIPLE medicines (a patient buys
    Paracetamol + Cough Syrup in one transaction). Invoice = the bill
    header (who, when, total). InvoiceItem = each line item within it.
    This is a classic one-to-many relationship, same shape as
    Order/OrderItem in any e-commerce system.
    """

    class PaymentMethod(models.TextChoices):
        CASH = 'CASH', 'Cash'
        CARD = 'CARD', 'Card'
        UPI = 'UPI', 'UPI'

    pharmacy = models.ForeignKey(
        Pharmacy, on_delete=models.PROTECT, related_name='invoices'
    )
    # PROTECT, not CASCADE: we NEVER want deleting a Pharmacy to silently
    # delete its billing history. Financial records must survive.

    customer_name = models.CharField(max_length=255, blank=True)
    customer_phone = models.CharField(max_length=15, blank=True)

    payment_method = models.CharField(
        max_length=10, choices=PaymentMethod.choices, default=PaymentMethod.CASH
    )

    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    gst_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['pharmacy', '-created_at']),  # "invoice history" queries
        ]

    def __str__(self):
        return f"Invoice #{self.id} - {self.pharmacy.name}"


class InvoiceItem(models.Model):
    """
    One line item within an invoice: "sold 2 units of Paracetamol at ₹20 each".

    IMPORTANT: we store `unit_price` and `medicine_name` as snapshot fields
    (copied from Inventory at the moment of sale), NOT just a foreign key
    to Inventory. WHY: if the pharmacy changes the price of Paracetamol
    next week, past invoices must still show the price the customer
    actually paid at the time. This is a common real-world data-integrity
    pattern — historical records should never silently change because a
    current record was updated.
    """
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items')
    inventory_item = models.ForeignKey(Inventory, on_delete=models.PROTECT)

    medicine_name = models.CharField(max_length=255)   # snapshot
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)  # snapshot
    quantity = models.PositiveIntegerField()

    @property
    def line_total(self):
        return self.unit_price * self.quantity

    def __str__(self):
        return f"{self.medicine_name} x{self.quantity}"